### PR TITLE
fix: github should check if email is verified

### PR DESCRIPTION
**Pull request by caarlos0**
Same as https://github.com/bitly/oauth2_proxy/pull/607. 

## Description

It doesn't really matter if the email is the primary one, what matters is if it is verified. 

## Motivation and Context

I didn't tested it, but probably a user can add a fake email within the needed domain, set it as primary, don't verify it, and use it to log in.

## How Has This Been Tested?

I've been using my fork with this change for months now.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by caarlos0** [comment]
build error seems unrelated to the changes...

**Comment by ploxiln** [comment]
The point of primary is that this can only return one email address. The first email address might not be the one that the verifier rules would approve, but a later email address might be. I think the only reliable way to get the it to pick the correct email address to get you logged in is to set "primary" accordingly. So, I think we want both - verified primary address.

It would be even better if this could return all verified addresses, or if the verifier function was passed in and this can check each verified address until it finds one that is approved. But that's a bigger refactor of oauth2_proxy I think ...

**Comment by caarlos0** [comment]
I agree that the best solution is to refactor to accept a list of emails... I can work on that if you want.

checking if it is primary and verified also sounds better... 

let me know what you think @ploxiln

**Comment by caarlos0** [comment]
updated to check if it is both primary and verified.

cc/ @ploxiln

**Comment by ploxiln** [comment]
Looks good to me 👍

**Comment by ploxiln** [comment]
(The failed test is `TestValidatorOverwriteEmailListViaRenameAndReplace` timing out, it is indeed flaky and unrelated, I fought with these watcher tests in https://github.com/ploxiln/oauth2_proxy/pull/3 and https://github.com/ploxiln/oauth2_proxy/pull/8 and seem to have fixed the flakyness with those changes.)

**Comment by caarlos0** [comment]
np, thanks! :D

**Pull request merged**
