### PR TITLE
Human friendly structured logging

### PR DESCRIPTION
**Pull request by terala**
Uses Zap to provide configurable and structured logging support.

## Description
All logging is changed to use structured logging in json. Zap library is used for this purpose and it is extremely light and fast. Program and request logs are now separated, though defaulted to stdout. The log level is defaulted to info, and is configurable.

Issue #90 for more information.

## Motivation and Context

Most enterprises aggregate logs into tools like splunk, elastic, etc so they can be processed further. This PR switches to structured logging, so log ingestion in to these tools becomes extremely easy.

## How Has This Been Tested?

Unit tests are added to test the ability to write the log to a file. Unit tests added to test log-level configuration.

## Checklist:
- [ ] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by terala** [comment]
@JoelSpeed Can you please review?

**Comment by JoelSpeed** [comment]
Hi @terala, before I review this, there is an existing PR open (#52) to restructure the login throughout this project. This allows users to choose their own templates for the logging structure. 

Could the configuration options in that PR not be used to define templates similar to that which Zap would give us? What is the benefit of this PR over #52?

**Comment by terala** [comment]
Hi @JoelSpeed,
There is a small overlap with #52, but the purpose of this PR is different. 
As mentioned in the PR description, this feature allows logging into `json` format, or the pseudo-`json` (human friendly) format. The intent of `json` logging is to pipe these logs into logging aggregators like elastic, splunk, etc. This is very useful when `oauth2_proxy` is run in an container (esp in k8s). Most container orchestration systems running in the enterprise usually pipe it to these log aggregators. So, a separate file rotation is usually not necessary.

These are the differences between #100 and #52:

|Feature | Structured Logging #100 | Auth / Standard Logging #52|
|-----|---|--|
| `json` Logging| Yes | No |
| Human Friendly | Partial (Human + mixed) | Yes |
| Selectable Log Messages| No | Yes|
| Builtin File Rolling | No. External rotators like `logrotate` is recommened | Yes|
|Structured| Yes  | No|

**Comment by terala** [comment]
Hi @JoelSpeed,
There is a small overlap with #52, but the purpose of this PR is different. 
As mentioned in the PR description, this feature allows logging into `json` format, or the pseudo-`json` (human friendly) format. The intent of `json` logging is to pipe these logs into logging aggregators like elastic, splunk, etc. This is very useful when `oauth2_proxy` is run in an container (esp in k8s). Most container orchestration systems running in the enterprise usually pipe it to these log aggregators. So, a separate file rotation is usually not necessary.

These are the differences between #100 and #52:

|Feature | Structured Logging #100 | Auth / Standard Logging #52|
|-----|---|--|
| `json` Logging| Yes | No |
| Human Friendly | Partial (Human + mixed) | Yes |
| Selectable Log Messages| No | Yes|
| Builtin File Rolling | No. External rotators like `logrotate` is recommened | Yes|
|Structured| Yes  | No|
 |Separate logs for http and Oauth2_proxy| Yes |No|

**Comment by terala** [comment]
@JoelSpeed Any thoughts?

**Comment by terala** [comment]
@JoelSpeed Is there any interest in this PR? If not, please let me know so I can close it.

**Comment by JoelSpeed** [comment]
@terala Could you please provide an example of some of the log lines that this PR generates?

**Comment by terala** [comment]
@JoelSpeed Typical output looks like this (for console option): It uses a mix of json and regular output formatting. 
```
2019-04-25T23:17:31.949-0700    INFO    oauth2_proxy/oauthproxy.go:217  OAuthProxy configured   {"provider": "Google", "clientid": "bazquux"}
2019-04-25T23:17:31.949-0700    INFO    oauth2_proxy/oauthproxy.go:225  Cookie Settings {"name": "_oauth2_proxy", "secure": true, "httponly": true, "expiry": "168h0m0s", "domain": "", "refresh": "disabled"}
2019-04-25T23:17:31.949-0700    INFO    oauth2_proxy/oauthproxy.go:189  Mapping path to upstream        {"path": "/", "upstream": "http://127.0.0.1:53157"}
2019-04-25T23:17:31.950-0700    INFO    oauth2_proxy/oauthproxy.go:217  OAuthProxy configured   {"provider": "Test Provider", "clientid": "bazquux"}
2019-04-25T23:17:31.950-0700    INFO    oauth2_proxy/oauthproxy.go:225  Cookie Settings {"name": "_oauth2_proxy", "secure": false, "httponly": true, "expiry": "168h0m0s", "domain": "", "refresh": "disabled"}
```

A full json log, when enabled via `-json-logging` flag dumps in the following way:

```
{"level":"INFO","timestamp":"2019-04-25T23:30:21.762-0700","caller":"oauth2_proxy/options.go:175","msg":"Validing OIDC Issuer URL","oidc_issuer_url":"https://nordstrom.oktapreview.com/oauth2/app_redacted"}
{"level":"DEBUG","timestamp":"2019-04-25T23:30:23.067-0700","caller":"oauth2_proxy/options.go:215","msg":"Discovered OIDC configuration","oidc_issuer_url":"https://nordstrom.oktapreview.com/oauth2/app_redacted","AuthURL":"https://nordstrom.oktapreview.com/oauth2/app_redacted/v1/authorize","TokenURL":"https://nordstrom.oktapreview.com/oauth2/app_redacted/v1/token"}
{"level":"INFO","timestamp":"2019-04-25T23:30:23.067-0700","caller":"oauth2_proxy/options.go:224","msg":"Configured OIDC scopes","scopes":"openid email profile"}
{"level":"INFO","timestamp":"2019-04-25T23:30:23.067-0700","caller":"oauth2_proxy/oauthproxy.go:189","msg":"Mapping path to upstream","path":"/","upstream":"https://localhost:10443"}
{"level":"INFO","timestamp":"2019-04-25T23:30:23.067-0700","caller":"oauth2_proxy/oauthproxy.go:217","msg":"OAuthProxy configured","provider":"OpenID Connect","clientid":"someclientid"}
{"level":"INFO","timestamp":"2019-04-25T23:30:23.067-0700","caller":"oauth2_proxy/oauthproxy.go:225","msg":"Cookie Settings","name":"_oauth2_proxy","secure":false,"httponly":true,"expiry":36000,"domain":"localhost","refresh":"disabled"}
{"level":"info","ts":"2019-04-25T23:30:23.068-0700","caller":"oauth2_proxy/http.go:64","msg":"HTTP Listening","listenAddress":":4180"}
```
Being fully json enabled makes it very easy to search when indexed via ElasticSearch, Splunk or similar log ingestion tools.

**Comment by terala** [comment]
Any update @JoelSpeed?

**Comment by JoelSpeed** [comment]
The reason I asked for sample logs is because I believe you can get a similar output to your Zap style log using the work done in #52 (which seems to be a more flexible logging implementation).

#52 allows you to set your own format for logging, for instance for standard requests the format is currently by default:
```
{{.Client}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}
```	

Though one could set it to:
```
{"client": {{.Client}},  "username": {{.Username}}, "timestamp": {{.Timestamp}}, "host": {{.Host}}, "method": {{.RequestMethod}},  "upstream": {{.Upstream}}, "uri": {{.RequestURI}}, "proto":{{.Protocol}}, "user agent": {{.UserAgent}}, "status": {{.StatusCode}}, "response size": {{.ResponseSize}}, "duration": {{.RequestDuration}}
```	
Which would then produce structured JSON log similar to that produced by your PR. If my thoughts here are correct then I think I would rather accept #52 over this PR as it should be slightly more flexible and allow both use cases.

**Comment by JoelSpeed** [comment]
I've merged #52 so am going to close this PR in favour of the changes in #52, please reopen if you still think there's merit to updating the logging architecture

**Comment by ploxiln** [comment]
A problem with just using a template that looks like json is that the values won't be escaped for json strings. E.g. you might try:

```
{"uri": "{{.RequestURI}}",  "user_agent": "{{.UserAgent}}", ...
```

but these values might theoretically have a backslash or double quote in them, and the result would not be machine-readable json.

But the go templates lib include some functions you can use, include `js`, I think maybe like so:

```
{"uri": {{js .RequestURI}},  "user_agent": {{js .UserAgent}}, ...
```

**Comment by JoelSpeed** [comment]
That's a very good point, thanks @ploxiln

**Pull request closed without merging**
