### PR TITLE
Add Quay links to ARM repositories

### LINKED ISSUE #16: [Request] Include Release & Docker build for Raspberry Pi (ARMv6/7 Architecture)
Not a bug. This is a general feature request to include an Arm version of the Docker build (via Travis-CI).

I was able to build the image myself successfully using the steps in [this Gist](https://gist.github.com/shbatm/e0f138da7418ab5970b3f89475195c49) (leaving here for anyone else who might want to reference), but it would be nice to have a pre-built Docker image for running on a Raspberry Pi.

Thanks!

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

Now that we have ARM releases and ARM Dockerfiles, I have set up automated builds of `master` and tags on two Quay repos for ARM (`quay.io/pusher/oauth2_proxy-armv6`, `quay.io/pusher/oauth2_proxy-amd64`).

(Ignore the markdown linting that got mixed in with this)

## Motivation and Context

Fixes #16 (@kskewes can you review this?)

## How Has This Been Tested?

Manually triggered builds of `master` which seem to have built from the Dockerfiles provided

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
> Should we update the makefile?
Yeah I'll do that

> I didn't realise would do multiple repos versus one repo with amd/arm tags
It's kinda annoying but Quay doesn't let you manage tags that way, so it has to be separate repos if we want to do automated builds using Quay, that or we work out how to get travis to push to Quay

**Comment by JoelSpeed** [comment]
@kskewes WDYT?

**Comment by JoelSpeed** [comment]
> It does seem a little weird to have different repos for all of the architectures as opposed to 1 repo with multiple tags.

Yeah I agree it's annoying but I've seen it done many times before (cough Hyperkube cough)

> Then users don't have to deal with it at all. OCI compliant runtimes can automatically pull the right image for their arch.

What happens for those that aren't compliant? 

I'm not saying multi-arch wouldn't be nice to have I just know very little about it right now so am wondering about making that a future project for someone who is enthusiastic about that stuff? (CC @icelynjennings WDYT?)

**Comment by JoelSpeed** [comment]
Reading through this document suggests using different repositories for multi-arch anyway? I guess that makes it easier to manage the tags across all of the repos? https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

**Comment by kfox1111** [comment]
heh. k8s did that for a while, because the google container registry that housed all the kubernetes images didn't support them until recently. That has now changed and k8s has switched to multiarch. see:
```
# grep image /etc/kubernetes/manifests/kube-apiserver.yaml 
    image: k8s.gcr.io/kube-apiserver:v1.13.2
```
The arch is now gone.

OCI basically is just the docker image format standard. read it to mean, one of 'docker, containerd, crio, hyper, singularity, etc]. As far as I know, all versions of supported docker including the distro ones like redhat's support multiarch manifests.

**Comment by kfox1111** [comment]
Hmm... I didn't think the manifest could reference other repositories.... thats... interesting....
That sparks an idea for another project...

Thanks. :)

One advantage is that you can look at all the tags and find which arches are supported from a website like dockerhub if there in the same repo. I guess it doesn't really matter though as you can just pull the manifest too.

**Comment by kskewes** [comment]
Shall I have a go in a fork/sample repo at Travis CI changes required for publishing?
Including docker images to single repo and binaries to Github?

We could add a `docker-push` target to the original single docker repo Makefile in the interim if it would be a suitable publishing workflow for the maintainers? 

Multi-arch is a good goal but requires changes to the build/publish steps like enabling docker experimental features.
This might be able to be achieved in Travis with right shell commands (sed + systemd restart) or prepending env var as required like this: 
`$ DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect nginxinc/nginx-unprivileged:alpine`
Something for later...?

FWIW, based image naming off Calico: https://quay.io/repository/calico/ctl?tab=tags and others...

**Comment by JoelSpeed** [comment]
I spoke with @kskewes on Slack and concluded for now that pushing images should be manual so that we don't have to have three separate Quay repos.

So I've made a `docker-push-all` target so that we can build and push releases manually.

I also removed the `--long` argument from the `git describe` as this means we get `vx.x.x-0-<SHA>` for tagged commits which is not what we want (try running the `v3.0.0` release with `--version` and see the output! (It's `oauth2_proxy v3.0.0-0-g7887272 (built with go1.10.7)`

@syscll You happy with this? I think we should get this merged and make the `v3.1.0` release

**Pull request merged**
