### PR TITLE
Adds banner flag

### PR DESCRIPTION
**Pull request by steakunderscore**
## Description

Adds a banner flag to override what's displayed on the main login page.

## Motivation and Context

This is to implement the suggestion in #193

## How Has This Been Tested?

Built docker image after applying patch in #190. Run in Kubernetes to load page and see that both `-banner='-'` and `-banner='My sweet banner'` worked.

## Checklist:

- [X] My change requires a change to the documentation or CHANGELOG.
- [X] I have updated the documentation/CHANGELOG accordingly.
- [X] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by RichardoC** [comment]
Do we know when a release with this is coming? This would be really handy!

**Comment by dcomas** [comment]
@JoelSpeed are you able to help with this?

**Comment by dcomas** [comment]
> LGTM, will be cutting a release next week hopefully

That is great! Thank you!

**Comment by steakunderscore** [comment]
Thanks @JoelSpeed !

**Pull request merged**
