### PR TITLE
Add upstream with static response

### PR DESCRIPTION
**Pull request by cgroschupp**
## Description

This change is necessary to use `oauth2_proxy` with the envoy ext_authz module. It is not  possible to configure the envoy ext_authz module to use the `/oauth2/auth` endpoint. The module calls the original request path and need a response code `200`.

https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto.html

## Motivation and Context

#219 

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation accordingly.
- [x] I have updated the CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by cgroschupp** [comment]
@JoelSpeed Can you please take a look at it?

**Comment by cgroschupp** [comment]
@syscll done

**Comment by syscll** [comment]
@JoelSpeed LGTM if you're happy?

**Comment by cgroschupp** [comment]
@JoelSpeed please review.

**Pull request merged**
