### PR TITLE
Made setting of proxied headers deterministic based on configuration alone

### PR DESCRIPTION
**Pull request by aeijdenberg**
## Description

Previously some headers that are normally set by the proxy (and may be
replied upstream for authorization decisiions) were not being set
depending on values in the users session.

This change ensure that if a given header is sometimes set, it will
always be either set or removed.

It might be worth considerating always deleting these headers if we
didn't add them.

## Motivation and Context

Stop malicious users being able to set headers that might be used for authorization.

## How Has This Been Tested?

It hasn't - will rely on unit tests when opening PR.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

## Extra notes

I'm about to head offline for a few weeks, so feel free to take this PR and merge a variant yourselves. I think it's worth considering being more aggressive about killing all of the headers regardless of what config is set, but figured this change should be more compatible.

### CODE REVIEW

**Comment by aeijdenberg** [comment]
@m-richo

**Comment by aeijdenberg** [comment]
@JoelSpeed - this shouldn't contain any breaking changes - my comments in the original PR are that it may be worth considering a different PR that is more aggressive and possibly breaking, however this one as implemented ought only be a security bug fix only (and had I been able to easily find a security address to report this issue to, I would have rather than opening the PR).

(I also don't believe I can easily make changes to this PR - I've changed roles and now longer have write access to the repository that this can been generated from)

**Comment by JoelSpeed** [comment]
> @JoelSpeed - this shouldn't contain any breaking changes - my comments in the original PR are that it may be worth considering a different PR that is more aggressive and possibly breaking, however this one as implemented ought only be a security bug fix only (and had I been able to easily find a security address to report this issue to, I would have rather than opening the PR).

My thought around this being breaking was that, users could be relying on the fact that we were proxying the headers we may be setting? ie, while this is a security fix, some people may be relying on that security bug, WDYT? 

> (I also don't believe I can easily make changes to this PR - I've changed roles and now longer have write access to the repository that this can been generated from)

In which case we _should_ be able to take the commits and create a new PR on a fork we can modify, assuming I don't already have push access (Normally forked PRs can be pushed to by owners of the original repo)

**Comment by steakunderscore** [comment]
I agree that this should have a mention in the change log. Otherwise I'm fine with this. @aeijdenberg you can always [checkout a branch based off this PR](https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request). Feel free to create a new PR to replace this one if you no longer have access to [govau/oauth2_proxy](https://github.com/govau/oauth2_proxy).

**Comment by aeijdenberg** [comment]
Abandoning this PR in favor of #226 (due to a job change, I no longer have write access to the repository from which this pull request originated).

**Pull request closed without merging**
