### PR TITLE
Okta Auth Provider PR

### PR DESCRIPTION
**Pull request by mikesiegel**
## Description

This change adds the Okta Auth Provider. It is based on @reedloden 's PR for the original bitly version[https://github.com/bitly/oauth2_proxy/pull/528/commits/6bbc9b981d183a5695c497cbb94ca9340d73bbfd](url)

## Motivation and Context

To support Okta authentication and authorization.  Okta is an SSO provider with a large market share that provides OIDC support. This change allows users to configure the oauth2_proxy to support Okta as an IDP.

## How Has This Been Tested?

Tested on golang 1.12.7 in front of an nginx server and Okta Preview.

## Checklist:

- [X ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ X] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
I just configured Okta with the generic OpenID provider and it seems to work fine (granted my usecase is very simple, just putting an application behind SSO without passing on any user details to the application). I'm curious what the benefit of this is compared to using the generic OpenID provider?

Also, I assume that additional functionality is why you need to use a custom authorization server. As you mentioned this isn't available on all Okta plans, can you add something to the docs about why this is required and if not completely required what the caveats are if this is not done and the default authorization server is used instead?

**Comment by mikesiegel** [comment]
You are correct, my mistake. I was trying to bring pusher in line with our bit.ly fork but now I see that's not necessary.

**Comment by ReillyProcentive** [comment]
I think it would be useful to have a section on configuring Okta in the docs. Currently the Openid connect provider only explains how to configure Dex, that section could possibly be expanded to cover multiple providers.

**Comment by steakunderscore** [comment]
I agree it would be useful to have some docs. @mikesiegel or @ReillyProcentive would one of you be able to push a PR for them?

**Comment by mikesiegel** [comment]
Sure thing @steakunderscore

**Comment by mikesiegel** [comment]
Opened https://github.com/pusher/oauth2_proxy/pull/235

**Pull request closed without merging**
