### PR TITLE
Proxy session store

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

This acts as the second half of #147, Implementing the new interface within the OAuth2 Proxy itself

## Motivation and Context

See #147 

## How Has This Been Tested?

I built an image and tested locally that I could perform an authentication flow

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I've built an image `quay.io/pusher/oauth2_proxy:pull-148` from this branch in case anyone has time to test this PR out (obviously including the changes in #147 as well)

**Comment by brianv0** [comment]
I created a PR against this branch with the Redis support.

**Comment by JoelSpeed** [comment]
I have been testing this today against one of our development clusters and everything seems to be working as expected for me /CC @syscll

**Comment by syscll** [comment]
LGTM - do we need to get #147 merged first?

**Comment by JoelSpeed** [comment]
Yep, this will need #147 merging first. I'm pretty happy with the combination of the two now, just waiting for another pair of eyes over the code

**Comment by JoelSpeed** [comment]
Yeah for some reason the Go 1.11 linting has started timing out consistently , though sometimes if you retry a few times you can trick it into working 😅 Is it worth building and testing against multiple Gos? 🤔

**Comment by syscll** [comment]
@JoelSpeed considering we only build using Go 1.12 in Docker, I suppose we might as well remove Go 1.11 from Travis?

**Comment by JoelSpeed** [comment]
> I suppose we might as well remove Go 1.11 from Travis?

I'l follow up with another PR for removing it, I don't see point in testing against multiple versions as you've pointed out

**Pull request merged**
