### PR TITLE
fix redirect url param handling

### PR DESCRIPTION
**Pull request by dt-rush**
See issue #9

### CODE REVIEW

**Comment by dt-rush** [comment]
Requesting review from @JoelSpeed 

Thanks for pushing this forward!

**Comment by dt-rush** [comment]
See [the corresponding issue](https://github.com/bitly/oauth2_proxy/issues/677) I had opened on the old, dead repo before I realized it was dead for some extra context. This PR not only fixes the user-supplied redirect URL not being honoured, but it also *actually uses it for both forming the request to the auth server and for listening for the callback on the appropriate path*. In OAuth, "redirect URL/path" and "callback URL/path" are not distinct - the former is how the spec calls it, and the latter is what it colloquially goes by for some people.

**Comment by JoelSpeed** [comment]
Hi @dt-rush, thanks for submitting this PR,

I've had a quick look over the PR and initially I agree with the proposed change, I'm at Kubecon this week and would like to have a further look into the code before accepting the PR.

I also plan to get #7 merged before accepting any additional PRs so please bear with me on that

**Comment by dt-rush** [comment]
@JoelSpeed no sweat! I've used the git diff as a patch for my deployment.

**Comment by JoelSpeed** [comment]
You'll want to rebase onto master to allow pick up the linting changes that have been merged to fix the CI

**Comment by JoelSpeed** [comment]
Would you please also add a note in the changelog file to mention that you've fixed the behaviour of this flag

**Comment by Ghazgkull** [comment]
@dt-rush Thanks for putting together this PR. This bug is affecting me as well and I'd love to see it merged.

@JoelSpeed As a motivated user, is there anything I can do to help get this PR merged?

**Comment by dt-rush** [comment]
@Ghazgkull I just rebased on master. Until this is merged, I've been simply using a patch which applies the changes to the source before building the binary.

@JoelSpeed, could we try to merge this now?

**Comment by dt-rush** [comment]
(Note: lint is failing in the travis build, but it complains about so many files that I suspect this is a goal for the repo, not a standard which we're currently meeting)

**Comment by ploxiln** [comment]
you should change the merge-target branch from "migration" to "master"

**Comment by JoelSpeed** [comment]
One final thing before this gets merged, could you please add a note to the Changelog describing the change you have made (Please see existing entries for the format)

**Comment by Ghazgkull** [comment]
@JoelSpeed Looks like @dt-rush submitted new changes which include the Changelog updates. Thanks, folks!

**Pull request merged**
