### PR TITLE
Implement ValidateSessionState for GitHubProvider

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
Refactors the setting of the Authorization header into getGitHubHeader.

Refs #382 

@JoelSpeed - at the risk of doing something you are already looking at, this change is untested, but _looks_ like it should fix the referenced problem.

### CODE REVIEW

**Comment by iain-buclaw-sociomantic** [comment]
Added changelog entry, however due to the nature of Github's alerting system, we'll have to wait at least three days for confirmation.

Running this patch on one node, I see no problems with the functionality of `validateToken` however.

**Comment by iain-buclaw-sociomantic** [comment]
I have received no further emails from GitHub so far, so knock wood it will stay that way.

**Comment by matiasgarciaisaia** [comment]
Would this be enough to release a v5.0.1?

Looks good to me, by the way.

Really thankful, @iain-buclaw-sociomantic 👍

**Comment by cpanato** [comment]
This will be released as 5.0.1? any plans to merge and release this fix? thanks!

**Pull request merged**
