### PR TITLE
Added pagination support for /user/teams github api

### PR DESCRIPTION
**Pull request by apratina**
## Description

Added pagination support for /user/teams github api

## Motivation and Context

When we are configuring both github org/team, then we are using /user/teams github api to find out if user is part of that github org/team. If user is part of more than 30 teams then the api response for /user/teams github api will be paginated across multiple pages. By adding pagination support we are checking user across all the teams.

## How Has This Been Tested?

Configure the service by setting the needed parameters that include:
- redirect-url
- github-org
- github-team
- client-id
- client-secret
- authenticated-emails-file
- cookie-secret
- cookie-domain
- cookie-secure
- provider
- login-url
- redeem-url
- validate-url

Launch the service in your IDE.

Hit the endpoint, http://localhost:4180

Login in using the sign in page

Before this change, it would return 403 permission denied, invalid account error message in browser

After this change, it would work fine and does not return any error. Logs also show that user is part of github org/team

Note: User who is part of more than 30 github team will face this issue.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@mbld does this superseed your change in #87?

**Comment by apratina** [comment]
@JoelSpeed : limit to per_page makes sense. But still that would just look into 100 teams, we may want to add pagination support to scroll thru teams more than that.

**Comment by mbld** [comment]
@JoelSpeed : Yes, that will superseed my changes.
@apratina: Many thanks for implementing the pagination 👍 As metioned by @apratina, we should also change the "lmit" parameter to "per_page". I have no preference about using #87 or include the limit->per_page change into this one ;) Please decide on what's easier for you ;)

**Comment by apratina** [comment]
@JoelSpeed @mbld : limit => per_page has been updated in this PR.

(Thanks for building this awesome proxy!!!)

**Comment by mbld** [comment]
Maybe also integrate the comment from @ploxiln about max value for "per_page" is 100, not 200. See  https://github.com/pusher/oauth2_proxy/pull/87#issuecomment-470358970

**Comment by apratina** [comment]
@mbld : Updated per_page value from 200 to 100.

**Comment by apratina** [comment]
@JoelSpeed @mbld : Can this be merged? Thanks.

**Comment by JoelSpeed** [comment]
@apratina Do you have time to take a look at my suggestion above? https://github.com/pusher/oauth2_proxy/pull/102#pullrequestreview-216742424

**Comment by apratina** [comment]
@JoelSpeed : let me look into this over the weekend. sorry got busy with other stuffs :)

**Comment by JoelSpeed** [comment]
Pinging @apratina, any chance you could take a look and fix this up as per comments above?

**Comment by midnightconman** [comment]
This should fix: #246

**Pull request merged**
